<?php

/**
 * Copyright (C) 2019 MwSpace s.r.l <https://mwspace.com>
 *
 * This file is part of namirial-php.
 *
 * You should have received a copy of the GNU General Public License
 * along with php-e-invoice-it.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Xela\Namirial;

class Client extends \SoapClient
{

    public function __construct(mixed $wsdl, array $options = null)
    {

        die('i xela ==)');

        parent::__construct($wsdl, $options);
    }

    public function __soapCall($function_name, array $arguments, array $options = null, $input_headers = null, array &$output_headers = null)
    {
        parent::__soapCall($function_name, $arguments, $options, $input_headers, $output_headers); // TODO: Change the autogenerated stub
    }

}
